.PHONY: clean All

All:
	@echo "----------Building project:[ Project-Group7 - Debug ]----------"
	@cd "Project-Group7" && "$(MAKE)" -f  "Project-Group7.mk"
clean:
	@echo "----------Cleaning project:[ Project-Group7 - Debug ]----------"
	@cd "Project-Group7" && "$(MAKE)" -f  "Project-Group7.mk" clean
